# games/duel/content/abilities.py
ABILITIES = {
    "basic_attack": {
        "name": "Basic Attack",
        "cost": {"energy": 0},
        "dice": {"type": "d4", "power_on": "roll"},
        "scaling": {"atk": 0.2},
        "damage_type": "physical",  # Uses weapon's physical atk or base atk
        "tags": ["attack", "physical"],
        "cooldown": 0,
    },
    "pass_turn": {
        "name": "Pass Turn",
        "cost": {"energy": 0},
        "dice": None,
        "tags": ["pass"],
        "cooldown": 0,
        "allow_while_stunned": True,
    },
    "fireball": {
        "name": "Fireball",
        "cost": {"mp": 10},
        "dice": {"type": "d6", "power_on": "roll"},
        "scaling": {"int": 0.4},  # Scale with int instead of atk
        "damage_type": "magic",
        "tags": ["spell", "attack", "magic"],
        "cooldown": 1,
        "classes": ["mage"],
        "on_hit_effects": [
            {"id": "hot_streak", "chance": 0.2, "log": "Has HOT STREAK!"}
        ],
    },
    "fire_blast": {
        "name": "Fire Blast",
        "cost": {"mp": 15},
        "dice": {"type": "d4", "power_on": "roll"},
        "scaling": {"int": 0.4},
        "damage_type": "magic",
        "tags": ["spell", "attack", "magic"],
        "cooldown": 8,
        "classes": ["mage"],
        "on_hit_effects": [
            {"id": "hot_streak", "chance": 1.0, "log": "Has HOT STREAK!"}
        ],
    },
    "arcane_barrage": {
        "name": "Arcane Barrage",
        "cost": {"mp": 15},
        "dice": {"type": "d6", "power_on": "roll"},
        "scaling": {"int": 0.4},
        "damage_type": "magic",
        "tags": ["spell", "attack", "magic"],
        "cooldown": 2,
        "classes": ["mage"],
        "hits": 3,
    },
    "overpower": {
        "name": "Overpower",
        "cost": {"rage": 0},
        "dice": {"type": "d4", "power_on": "roll"},
        "scaling": {"atk": 0.6},
        "damage_type": "physical",
        "tags": ["attack", "physical"],
        "cooldown": 1,
        "classes": ["warrior"],
        "resource_gain": {"rage": "damage"},
    },
    "victory_rush": {
        "name": "Victory Rush",
        "cost": {"rage": 0},
        "dice": {"type": "d2", "power_on": "roll"},
        "scaling": {"atk": 0.5},
        "damage_type": "physical",
        "tags": ["attack", "physical"],
        "cooldown": 20,
        "charges": 2,
        "classes": ["warrior"],
        "heal_scaling": {"atk": 1.6},
        "heal_dice": {"type": "d8", "power_on": "roll"},
        "resource_gain": {"rage": 5},
    },
    "mortal_strike": {
        "name": "Mortal Strike",
        "cost": {"rage": 30},
        "dice": {"type": "d6", "power_on": "roll"},
        "scaling": {"atk": 2.0},
        "damage_type": "physical",
        "tags": ["attack", "physical"],
        "cooldown": 0,
        "classes": ["warrior"],
    },
    "die_by_sword": {
        "name": "Die by the Sword",
        "cost": {"rage": 0},
        "dice": None,
        "tags": ["defense"],
        "cooldown": 10,
        "classes": ["warrior"],
        "self_effects": [
            {"id": "die_by_sword", "duration": 2, "log": "becomes immune to physical damage."},
            {"id": "die_by_sword_mitigation", "duration": 2, "log": "reduces incoming damage by 30%."},
        ],
    },
    "execute": {
        "name": "Execute",
        "cost": {"rage": 20},
        "dice": {"type": "d6", "power_on": "roll"},
        "scaling": {"atk": 1.5},
        "damage_type": "physical",
        "tags": ["attack", "physical"],
        "cooldown": 1,
        "classes": ["warrior"],
        "requires_target_hp_below": 0.2,
    },
    "dragon_roar": {
        "name": "Dragon Roar",
        "cost": {"rage": 10},
        "dice": {"type": "d6", "power_on": "roll"},
        "scaling": {"atk": 0.8},
        "damage_type": "physical",
        "tags": ["attack", "physical", "aoe"],
        "requires_target": False,
        "cooldown": 25,
        "classes": ["warrior"],
        "always_crit": True,
        "ignore_physical_reduction": True,
        "dot": {
            "id": "dragon_roar_bleed",
            "duration": 4,
            "school": "physical",
            "scaling": {"atk": 0.4},
            "dice": {"type": "d2", "power_on": "roll"},
        },
    },
    "ignore_pain": {
        "name": "Ignore Pain",
        "cost": {"rage": 5},
        "dice": None,
        "tags": ["defense"],
        "cooldown": 6,
        "classes": ["warrior"],
        "absorb": {
            "scaling": {"atk": 0.5},
            "dice": {"type": "d4", "power_on": "roll"},
            "source_name": "Ignore Pain",
            "effect_id": "ignore_pain",
        },
        "self_effects": [
            {"id": "ignore_pain", "duration": 8, "log": "Fights through pain."}
        ],
    },
    "pyroblast": {
        "name": "Pyroblast",
        "cost": {"mp": 20},
        "dice": {"type": "d10", "power_on": "roll"},
        "scaling": {"int": 2.0},
        "damage_type": "magic",
        "tags": ["spell", "attack", "magic"],
        "cooldown": 0,
        "classes": ["mage"],
        "requires_effect": "hot_streak",
        "consume_effect": "hot_streak",
    },
    "iceblock": {
        "name": "Ice Block",
        "cost": {"mp": 0},
        "dice": None,
        "tags": ["defense", "spell"],
        "priority_defensive": True,
        "cooldown": 20,
        "classes": ["mage"],
        "self_effects": [
            {"id": "iceblock", "duration": 3, "log": "encases themselves in ice."},
            {"type": "dispel", "category": "dot", "school": "magical"},
        ],
    },
    "blink": {
        "name": "Blink",
        "cost": {"mp": 0},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 6,
        "classes": ["mage"],
        "self_effects": [
            {"id": "blink", "duration": 2, "log": "blinks out of reach."}
        ],
    },
    "ring_of_ice": {
        "name": "Ring of Ice",
        "cost": {"mp": 0},
        "dice": None,
        "tags": ["spell", "control"],
        "cooldown": 3,
        "classes": ["mage"],
        "target_effects": [
            {"id": "ring_of_ice_freeze", "duration": 1, "log": "freezes the enemy solid."}
        ],
    },
    "ice_barrier": {
        "name": "Ice Barrier",
        "cost": {"mp": 10},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 15,
        "classes": ["mage"],
        "absorb": {
            "scaling": {"int": 0.9},
            "dice": {"type": "d6", "power_on": "roll"},
            "source_name": "Ice Barrier",
        },
        "self_effects": [
            {"id": "ice_barrier", "duration": 8},
        ],
    },
    "cheap_shot": {
        "name": "Cheap Shot",
        "cost": {"energy": 0},
        "dice": None,
        "tags": ["control"],
        "cooldown": 3,
        "classes": ["rogue"],
        "target_effects": [
            {"id": "stunned", "duration": 1, "log": "Target stunned."}
        ],
    },
    "kidney_shot": {
        "name": "Kidney Shot",
        "cost": {"energy": 5},
        "dice": None,
        "tags": ["control"],
        "cooldown": 10,
        "classes": ["rogue"],
        "target_effects": [
            {"id": "stunned", "duration": 2, "log": "Target stunned."}
        ],
    },
    "vanish": {
        "name": "Vanish",
        "cost": {"energy": 0},
        "dice": None,
        "tags": ["stealth", "defense"],
        "priority_defensive": True,
        "cooldown": 15,
        "classes": ["rogue"],
        "self_effects": [
            {
                "id": "stealth",
                "duration": 3,
                "overrides": {"regen": {"hp": 15, "energy": 5}},
                "log": "vanishes into the shadows.",
            }
        ],
    },
    "cloak": {
        "name": "Cloak of Shadows",
        "cost": {"energy": 0},
        "dice": None,
        "tags": ["defense"],
        "cooldown": 20,
        "classes": ["rogue"],
        "self_effects": [
            {"id": "cloak_of_shadows", "duration": 2, "log": "is shrouded from magic."},
            {"type": "dispel", "category": "dot", "school": "magical"},
        ],
    },
    "eviscerate": {
        "name": "Eviscerate",
        "cost": {"energy": 30},
        "dice": {"type": "d10", "power_on": "roll"},
        "scaling": {"atk": 1.2},
        "damage_type": "physical",
        "tags": ["attack", "physical"],
        "cooldown": 1,
        "classes": ["rogue"],
    },
    "evasion": {
        "name": "Evasion",
        "cost": {"energy": 0},
        "dice": None,
        "tags": ["defense"],
        "cooldown": 20,
        "classes": ["rogue"],
        "self_effects": [
            {"id": "evasion", "duration": 2, "log": "becomes incredibly evasive."}
        ],
    },
    "thistle_tea": {
        "name": "Thistle Tea",
        "cost": {"energy": 30},
        "dice": None,
        "tags": ["buff"],
        "cooldown": 15,
        "classes": ["rogue"],
        "self_effects": [
            {"id": "thistle_tea", "duration": 3, "log": "sips Thistle Tea."}
        ],
    },
    "shadow_blade": {
        "name": "Shadow Blade",
        "cost": {"energy": 15},
        "dice": {"type": "d6", "power_on": "roll"},
        "scaling": {"atk": 0.5},
        "stealth_bonus": {
            "dice": {"type": "d8", "power_on": "roll"},
            "scaling": {"atk": 1.3},
            "log": "Empowered by stealth.",
        },
        "damage_type": "physical",
        "tags": ["attack", "physical"],
        "cooldown": 0,
        "classes": ["rogue"],
        "on_hit_effects": [
            {"id": "ambush", "chance": 0.2, "log": "Has Ambush!"}
        ],
        "stealth_on_hit_effects": [
            {"id": "ambush", "chance": 1.0, "log": "Has Ambush!"}
        ],
    },
    "ambush": {
        "name": "Ambush",
        "cost": {"energy": 15},
        "dice": {"type": "d6", "power_on": "roll"},
        "scaling": {"atk": 1.7},
        "damage_type": "physical",
        "tags": ["attack", "physical"],
        "cooldown": 0,
        "classes": ["rogue"],
        "requires_effect": "ambush",
        "consume_effect": "ambush",
    },
    "fury_of_azzinoth": {
        "name": "Fury of Azzinoth",
        "display_color": "#1EFF00",
        "cost": {"energy": 0},
        "dice": {"type": "d6", "power_on": "roll"},
        "scaling": {"atk": 0.2},
        "damage_type": "physical",
        "tags": ["attack", "physical"],
        "cooldown": 25,
        "hits": 4,
        "requires_weapon": "twin_blades_azzinoth",
        "requires_weapon_log": "Twin Blades of Azzinoth must be equipped.",
        "heal_from_dealt_damage": True,
    },
    "bear": {
        "name": "Bear Form",
        "cost": {"mp": 0},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 0,
        "classes": ["druid"],
        "self_effects": [
            {"id": "bear_form", "duration": 999, "log": "shifts into Bear Form."}
        ],
    },
    "maul": {
        "name": "Maul",
        "cost": {"rage": 0},
        "dice": {"type": "d4", "power_on": "roll"},
        "scaling": {"atk": 0.3},
        "damage_type": "physical",
        "tags": ["attack", "physical"],
        "cooldown": 0,
        "classes": ["druid"],
        "requires_form": "bear_form",
        "requires_form_log": "Must be in Bear Form.",
        "resource_gain": {"rage": "damage_x3"},
    },
    "swipe": {
        "name": "Swipe",
        "cost": {"rage": 0},
        "dice": {"type": "d8", "power_on": "roll"},
        "scaling": {"atk": 0.5},
        "damage_type": "physical",
        "target_mode": "aoe_enemy",
        "tags": ["attack", "physical", "aoe"],
        "cooldown": 10,
        "classes": ["druid"],
        "requires_form": "bear_form",
        "requires_form_log": "Must be in Bear Form.",
    },
    "frenzied_regeneration": {
        "name": "Frenzied Regeneration",
        "cost": {"rage": 0},
        "dice": None,
        "tags": ["defense"],
        "cooldown": 30,
        "classes": ["druid"],
        "requires_form": "bear_form",
        "requires_form_log": "Must be in Bear Form.",
    },
    "barkskin": {
        "name": "Barkskin",
        "cost": {"rage": 0},
        "dice": None,
        "tags": ["defense"],
        "cooldown": 15,
        "classes": ["druid"],
        "requires_form": "bear_form",
        "requires_form_log": "Must be in Bear Form.",
        "self_effects": [
            {"id": "barkskin", "duration": 3, "log": "hardens their barkskin."}
        ],
    },
    "cat": {
        "name": "Cat Form",
        "cost": {"mp": 0},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 0,
        "classes": ["druid"],
        "self_effects": [
            {"id": "cat_form", "duration": 999, "log": "shifts into Cat Form."}
        ],
    },
    "claw": {
        "name": "Claw",
        "cost": {"energy": 10},
        "dice": {"type": "d4", "power_on": "roll"},
        "scaling": {"atk": 1.0},
        "damage_type": "physical",
        "tags": ["attack", "physical"],
        "cooldown": 0,
        "classes": ["druid"],
        "requires_form": "cat_form",
        "requires_form_log": "Must be in Cat Form.",
        "on_hit_effects": [
            {"id": "rip_ready", "chance": 0.25, "log": "Has Rip!"}
        ],
    },
    "shred": {
        "name": "Shred",
        "cost": {"energy": 15},
        "dice": {"type": "d4", "power_on": "roll"},
        "scaling": {"atk": 1.5},
        "damage_type": "physical",
        "tags": ["attack", "physical"],
        "cooldown": 2,
        "classes": ["druid"],
        "requires_form": "cat_form",
        "requires_form_log": "Must be in Cat Form.",
    },
    "maim": {
        "name": "Maim",
        "cost": {"energy": 10},
        "dice": None,
        "tags": ["control"],
        "cooldown": 15,
        "classes": ["druid"],
        "requires_form": "cat_form",
        "requires_form_log": "Must be in Cat Form.",
        "target_effects": [
            {"id": "stunned", "duration": 3, "log": "Stuns enemy."}
        ],
    },
    "rip": {
        "name": "Rip",
        "cost": {"energy": 0},
        "dice": {"type": "d8", "power_on": "roll"},
        "scaling": {"atk": 2.0},
        "damage_type": "physical",
        "tags": ["attack", "physical"],
        "cooldown": 0,
        "classes": ["druid"],
        "requires_form": "cat_form",
        "requires_form_log": "Must be in Cat Form.",
        "requires_effect": "rip_ready",
        "consume_effect": "rip_ready",
        "resource_gain": {"energy": 5},
    },
    "prowl": {
        "name": "Prowl",
        "cost": {"energy": 0},
        "dice": None,
        "tags": ["stealth", "defense"],
        "priority_defensive": True,
        "cooldown": 15,
        "classes": ["druid"],
        "requires_form": "cat_form",
        "requires_form_log": "Must be in Cat Form.",
        "self_effects": [
            {
                "id": "stealth",
                "duration": 3,
                "overrides": {"regen": {"energy": 15}},
                "log": "slips into a prowling stealth.",
            }
        ],
    },
    "moonkin": {
        "name": "Moonkin Form",
        "cost": {"mp": 0},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 0,
        "classes": ["druid"],
        "self_effects": [
            {"id": "moonkin_form", "duration": 999, "log": "shifts into Moonkin Form."}
        ],
    },
    "wrath": {
        "name": "Wrath",
        "cost": {"mp": 15},
        "dice": {"type": "d6", "power_on": "roll"},
        "scaling": {"int": 1.0},
        "damage_type": "magic",
        "tags": ["spell", "attack", "magic"],
        "cooldown": 0,
        "classes": ["druid"],
        "requires_form": "moonkin_form",
        "requires_form_log": "Must be in Moonkin Form.",
        "on_hit_effects": [
            {"id": "starfire_ready", "chance": 0.25, "log": "Has Starfire!"}
        ],
    },
    "starfire": {
        "name": "Starfire",
        "cost": {"mp": 20},
        "dice": {"type": "d6", "power_on": "roll"},
        "scaling": {"int": 2.0},
        "damage_type": "magic",
        "tags": ["spell", "attack", "magic"],
        "cooldown": 0,
        "classes": ["druid"],
        "requires_form": "moonkin_form",
        "requires_form_log": "Must be in Moonkin Form.",
        "requires_effect": "starfire_ready",
        "consume_effect": "starfire_ready",
    },
    "cyclone": {
        "name": "Cyclone",
        "cost": {"mp": 0},
        "dice": None,
        "tags": ["control", "spell"],
        "cooldown": 20,
        "classes": ["druid"],
        "requires_form": "moonkin_form",
        "requires_form_log": "Must be in Moonkin Form.",
        "target_effects": [
            {"id": "cyclone", "duration": 2, "log": "Trapps enemy in a cyclone."}
        ],
    },
    "typhoon": {
        "name": "Typhoon",
        "cost": {"mp": 0},
        "dice": None,
        "tags": ["control", "spell"],
        "cooldown": 5,
        "classes": ["druid"],
        "requires_form": "moonkin_form",
        "requires_form_log": "Must be in Moonkin Form.",
        "target_effects": [
            {
                "id": "typhoon_disoriented",
                "duration": 2,
                "log": "Blasts enemy away.",
            }
        ],
    },
    "tree": {
        "name": "Tree Form",
        "cost": {"mp": 0},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 0,
        "classes": ["druid"],
        "self_effects": [
            {"id": "tree_form", "duration": 999, "log": "shifts into Tree Form."}
        ],
    },
    "wild_growth": {
        "name": "Wild Growth",
        "cost": {"mp": 70},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 0,
        "classes": ["druid"],
        "requires_form": "tree_form",
        "requires_form_log": "Must be in Tree Form.",
    },
    "regrowth": {
        "name": "Regrowth",
        "cost": {"mp": 15},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 15,
        "classes": ["druid"],
        "requires_form": "tree_form",
        "requires_form_log": "Must be in Tree Form.",
    },
    "innervate": {
        "name": "Innervate",
        "cost": {"mp": 0},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 50,
        "classes": ["druid"],
        "requires_form": "tree_form",
        "requires_form_log": "Must be in Tree Form.",
    },
    "rage_within": {
        "name": "The Rage Within",
        "cost": {"rage": 0},
        "dice": None,
        "tags": ["passive"],
        "cooldown": 0,
        "classes": ["druid"],
    },
    "teleport": {
        "name": "Demonic Circle: Teleport",
        "cost": {"mp": 0},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 30,
        "classes": ["warlock"],
        "requires_circle": True,
        "self_effects": [{"id": "blink", "duration": 2, "overrides": {"miss_log": "Target returned to their dark ward — Miss."}, "log": "teleports via Demonic Circle."}],
    },
    "demonic_circle": {
        "name": "Demonic Circle",
        "cost": {"mp": 0},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 0,
        "classes": ["warlock"],
        "self_effects": [{"id": "demonic_circle", "duration": 999, "log": "summons a Demonic Circle."}],
    },
    "demonic_gateway": {
        "name": "Demonic Gateway",
        "cost": {"mp": 0},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 25,
        "classes": ["warlock"],
        "self_effects": [{"id": "blink", "duration": 2, "overrides": {"miss_log": "Target fled through the portal — Miss."}, "log": "slips through a Demonic Gateway."}],
    },
    "fear": {
        "name": "Fear",
        "cost": {"mp": 5},
        "dice": None,
        "tags": ["spell", "control"],
        "cooldown": 6,
        "classes": ["warlock"],
        "target_effects": [{"id": "stunned", "duration": 1, "overrides": {"cant_act_reason": "feared"}, "log": "Enemy is feared and cannot act."}],
    },
    "healthstone": {
        "name": "Healthstone",
        "cost": {"mp": 0},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 8,
        "classes": ["warlock"],
    },
    "drain_life": {
        "name": "Drain Life",
        "cost": {"mp": 5},
        "dice": {"type": "d6", "power_on": "roll"},
        "scaling": {"int": 0.8},
        "damage_type": "magic",
        "tags": ["spell", "attack", "magic"],
        "cooldown": 3,
        "classes": ["warlock"],
        "heal_from_damage": 1.0,
    },
    "summon_imp": {
        "name": "Summon Imp",
        "cost": {"mp": 10},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 0,
        "classes": ["warlock"],
    },
    "corruption": {
        "name": "Corruption",
        "cost": {"mp": 10},
        "dice": {"type": "d4", "power_on": "roll"},
        "scaling": {"int": 3.0},
        "damage_type": "magic",
        "tags": ["spell", "attack", "magic"],
        "cooldown": 8,
        "classes": ["warlock"],
        "dot": {"id": "corruption", "duration": 8},
    },
    "unstable_affliction": {
        "name": "Unstable Affliction",
        "cost": {"mp": 20},
        "dice": {"type": "d4", "power_on": "roll"},
        "scaling": {"int": 3.5},
        "damage_type": "magic",
        "tags": ["spell", "attack", "magic"],
        "cooldown": 10,
        "classes": ["warlock"],
        "dot": {"id": "unstable_affliction", "duration": 10},
    },
    "agony": {
        "name": "Agony",
        "cost": {"mp": 20},
        "dice": None,
        "tags": ["spell", "attack", "magic"],
        "cooldown": 10,
        "classes": ["warlock"],
        "dot": {"id": "agony", "duration": 10},
        "reject_if_active": True,
    },
    "dark_pact": {
        "name": "Dark Pact",
        "cost": {"mp": 15},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 30,
        "classes": ["warlock"],
        "hp_sacrifice": {"pct": 0.20, "min_hp_leave": 1},
        "grant_absorb_from_sacrifice": {"mult": 2.0, "effect_id": "dark_pact", "duration": 3},
    },
    "unending_resolve": {
        "name": "Unending Resolve",
        "cost": {"mp": 5},
        "dice": None,
        "tags": ["spell", "defense"],
        "priority_defensive": True,
        "cooldown": 40,
        "classes": ["warlock"],
        "self_effects": [
            {"id": "unending_resolve", "duration": 1, "log": "becomes immune to all damage for a turn."}
        ],
    },
    "rampage": {
        "name": "Rampage",
        "cost": {"rage": 15},
        "dice": {"type": "d4", "power_on": "roll"},
        "scaling": {"atk": 0.7},
        "damage_type": "physical",
        "tags": ["attack", "physical"],
        "cooldown": 0,
        "classes": ["warrior"],
        "hits": 2,
    },

    "crusader_strike": {
        "name": "Crusader Strike",
        "cost": {"mp": 0},
        "resource_gain": {"mp": 5},
        "dice": {"type": "d6", "power_on": "roll"},
        "scaling": {"atk": 0.4},
        "damage_type": "physical",
        "tags": ["attack", "physical"],
        "cooldown": 0,
        "classes": ["paladin"],
        "on_hit_effects": [
            {"id": "paladin_final_verdict_empowered", "chance": 0.3, "log": "Has Final Verdict Empowered!"}
        ],
    },
    "judgment": {
        "name": "Judgment",
        "cost": {"mp": 5},
        "dice": {"type": "d6", "power_on": "roll"},
        "scaling": {"atk": 1.0},
        "damage_type": "magic",
        "tags": ["spell", "attack", "magic"],
        "cooldown": 3,
        "classes": ["paladin"],
    },
    "final_verdict": {
        "name": "Final Verdict",
        "cost": {"mp": 10},
        "dice": {"type": "d8", "power_on": "roll"},
        "scaling": {"atk": 1.1},
        "damage_type": "physical",
        "tags": ["attack", "physical"],
        "cooldown": 6,
        "classes": ["paladin"],
    },
    "holy_light": {
        "name": "Holy Light",
        "cost": {"mp": 30},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 0,
        "classes": ["paladin"],
    },
    "hammer_of_justice": {
        "name": "Hammer of Justice",
        "cost": {"mp": 0},
        "dice": None,
        "tags": ["control"],
        "cooldown": 15,
        "classes": ["paladin"],
        "target_effects": [
            {"id": "stunned", "duration": 2, "log": "Enemy is stunned."}
        ],
    },
    "divine_shield": {
        "name": "Divine Shield",
        "cost": {"mp": 0},
        "dice": None,
        "tags": ["spell", "defense"],
        "priority_defensive": True,
        "cooldown": 25,
        "classes": ["paladin"],
        "self_effects": [
            {"id": "divine_shield", "duration": 2, "log": "is protected by Divine Shield."},
            {"type": "dispel", "category": "dot", "school": "magical"},
        ],
    },
    "shield_of_vengeance": {
        "name": "Shield of Vengeance",
        "cost": {"mp": 10},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 25,
        "classes": ["paladin"],
        "absorb": {
            "scaling": {"atk": 0.8},
            "dice": {"type": "d6", "power_on": "roll"},
            "source_name": "Shield of Vengeance",
            "effect_id": "shield_of_vengeance",
        },
        "self_effects": [
            {"id": "shield_of_vengeance", "duration": 8}
        ],
    },
    "lay_on_hands": {
        "name": "Lay on Hands",
        "cost": {"mp": 20},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 50,
        "classes": ["paladin"],
    },

    "avenging_wrath": {
        "name": "Avenging Wrath",
        "cost": {"mp": 20},
        "dice": None,
        "tags": ["spell", "buff"],
        "cooldown": 20,
        "classes": ["paladin"],
        "self_effects": [
            {"id": "avenging_wrath", "duration": 4, "log": "Abilities are empowered by Avenging Wrath!"}
        ],
    },
    "shield": {
        "name": "Power Word: Shield",
        "display_color": "#FFFFFF",
        "cost": {"mp": 20},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 8,
        "classes": ["priest"],
        "absorb": {
            "scaling": {"int": 1.0},
            "dice": {"type": "d6", "power_on": "roll"},
            "source_name": "Power Word: Shield",
        },
        "self_effects": [
            {"id": "power_word_shield", "duration": 8, "log": "Shielded by the Light."}
        ],
    },
    "mind_flay": {
        "name": "Mind Flay",
        "display_color": "#FFFFFF",
        "cost": {"mp": 5},
        "dice": {"type": "d4", "power_on": "roll"},
        "scaling": {"int": 0.4},
        "damage_type": "magic",
        "tags": ["spell", "attack", "magic"],
        "cooldown": 0,
        "classes": ["priest"],
        "on_hit_effects": [
            {"id": "mind_blast_empowered", "chance": 0.4, "log": "Mind Blast is empowered!"}
        ],
    },
    "mind_blast": {
        "name": "Mind Blast",
        "display_color": "#FFFFFF",
        "cost": {"mp": 15},
        "dice": {"type": "d6", "power_on": "roll"},
        "scaling": {"int": 0.9},
        "damage_type": "magic",
        "tags": ["spell", "attack", "magic"],
        "cooldown": 3,
        "classes": ["priest"],
        "on_hit_effects": [
            {"id": "shadowy_insight", "chance": 0.4, "log": "Has Shadowy Insight!"}
        ],
    },
    "vampiric_touch": {
        "name": "Vampiric Touch",
        "display_color": "#FFFFFF",
        "cost": {"mp": 12},
        "dice": {"type": "d6", "power_on": "roll"},
        "scaling": {"int": 3.0},
        "damage_type": "magic",
        "tags": ["spell", "attack", "magic"],
        "cooldown": 8,
        "classes": ["priest"],
        "dot": {"id": "vampiric_touch", "duration": 6},
    },
    "devouring_plague": {
        "name": "Devouring Plague",
        "display_color": "#FFFFFF",
        "cost": {"mp": 25},
        "dice": {"type": "d4", "power_on": "roll"},
        "scaling": {"int": 2.0},
        "damage_type": "magic",
        "tags": ["spell", "attack", "magic"],
        "cooldown": 0,
        "classes": ["priest"],
        "dot": {"id": "devouring_plague", "duration": 4},
        "requires_effect": "shadowy_insight",
        "consume_effect": "shadowy_insight",
    },
    "penance": {
        "name": "Penance",
        "display_color": "#FFFFFF",
        "cost": {"mp": 12},
        "dice": {"type": "d4", "power_on": "roll"},
        "scaling": {"int": 0.4},
        "damage_type": "magic",
        "tags": ["spell", "attack", "magic"],
        "cooldown": 8,
        "classes": ["priest"],
        "hits": 3,
        "shared_cooldown_with": ["penance_self"],
    },
    "penance_self": {
        "name": "Penance (Self)",
        "display_color": "#FFFFFF",
        "cost": {"mp": 12},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 8,
        "classes": ["priest"],
        "shared_cooldown_with": ["penance"],
    },
    "pain_supp": {
        "name": "Pain Suppression",
        "display_color": "#FFFFFF",
        "cost": {"mp": 0},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 20,
        "classes": ["priest"],
        "self_effects": [
            {"id": "pain_suppression", "duration": 3, "log": "reduces incoming damage with Pain Suppression."}
        ],
    },
    "mindgames": {
        "name": "Mindgames",
        "display_color": "#FFFFFF",
        "cost": {"mp": 15},
        "dice": None,
        "tags": ["spell", "control"],
        "cooldown": 20,
        "classes": ["priest"],
        "priority_control": True,
        "target_effects": [
            {"id": "mindgames", "duration": 1, "log": "Assaults the enemy's mind."}
        ],
    },
    "flash_heal": {
        "name": "Flash Heal",
        "display_color": "#FFFFFF",
        "cost": {"mp": 25},
        "dice": {"type": "d8", "power_on": "roll"},
        "tags": ["spell", "defense"],
        "cooldown": 3,
        "classes": ["priest"],
    },
    "mass_dispel": {
        "name": "Mass Dispel",
        "display_color": "#FFFFFF",
        "cost": {"mp": 12},
        "dice": None,
        "tags": ["spell", "control"],
        "cooldown": 20,
        "classes": ["priest"],
    },
    "death": {
        "name": "Shadow Word: Death",
        "display_color": "#FFFFFF",
        "cost": {"mp": 0},
        "dice": {"type": "d6", "power_on": "roll"},
        "scaling": {"int": 1.0},
        "damage_type": "magic",
        "tags": ["spell", "attack", "magic"],
        "cooldown": 5,
        "classes": ["priest"],
    },
    "shadowfiend": {
        "name": "Shadowfiend",
        "display_color": "#FFFFFF",
        "cost": {"mp": 20},
        "dice": None,
        "tags": ["spell", "defense"],
        "cooldown": 50,
        "classes": ["priest"],
        "self_effects": [
            {"id": "shadowfiend", "duration": 5, "log": "summons a Shadowfiend."}
        ],
    },

}
