PETS = {
    "imp": {
        "id": "imp",
        "name": "Imp",
        "entity_type": "demon",
        "hp": 5,
        "school": "magical",
        "subschool": "fire",
        "max_count": 3,
        "behavior_id": "imp_firebolt",
        "behavior": "imp_firebolt",
        "action_text": "casts Firebolt",
        "display": {
            "war_council": True,
            "label": "Imp",
            "color": "#FF7A59",
            "priority": 20,
        },
    },
    "shadowfiend": {
        "id": "shadowfiend",
        "name": "Shadowfiend",
        "entity_type": "demon",
        "hp": 20,
        "school": "physical",
        "duration": 5,
        "max_count": 1,
        "behavior_id": "shadowfiend_melee_mana",
        "behavior": "shadowfiend_melee_mana",
        "action_text": "melees the target",
        "display": {
            "war_council": True,
            "label": "Shadowfiend",
            "color": "#8C7AE6",
            "priority": 30,
        },
    },
    "frostsaber": {
        "id": "frostsaber",
        "template_id": "frostsaber",
        "name": "Frostsaber",
        "entity_type": "beast",
        "hp": 20,
        "atk": 6,
        "int": 2,
        "school": "physical",
        "max_count": 1,
        "behavior_id": "hunter_basic_plus_special",
        "summon_group": "hunter_companion",
        "persistent_owner_memory": True,
        "permanent_death": True,
        "basic_attack": {"school": "physical", "stat": "atk", "scaling": 1.0, "dice": "d4", "action_text": "melees the target"},
        "specials": {"bite": {"action_text": "bites the target"}},
        "special_id": "bite",
        "special_chance": 0.30,
        "display": {
            "war_council": True,
            "label": "Frostsaber",
            "color": "#AAD372",
            "priority": 25,
        },
    },
    "emerald_serpent": {
        "id": "emerald_serpent",
        "template_id": "emerald_serpent",
        "name": "Emerald Serpent",
        "entity_type": "beast",
        "hp": 15,
        "atk": 4,
        "int": 10,
        "school": "magical",
        "subschool": "nature",
        "max_count": 1,
        "behavior_id": "hunter_basic_plus_special",
        "summon_group": "hunter_companion",
        "persistent_owner_memory": True,
        "permanent_death": True,
        "basic_attack": {"school": "physical", "stat": "atk", "scaling": 1.0, "dice": "d4", "action_text": "melees the target"},
        "specials": {"lightning_breath": {"action_text": "breathes lightning", "school": "magical", "subschool": "nature"}},
        "special_id": "lightning_breath",
        "special_chance": 0.30,
        "display": {
            "war_council": True,
            "label": "Emerald Serpent",
            "color": "#AAD372",
            "priority": 25,
        },
    },
    "barrens_boar": {
        "id": "barrens_boar",
        "template_id": "barrens_boar",
        "name": "Barrens Boar",
        "entity_type": "beast",
        "hp": 30,
        "atk": 4,
        "int": 0,
        "school": "physical",
        "max_count": 1,
        "behavior_id": "hunter_basic_plus_special",
        "summon_group": "hunter_companion",
        "persistent_owner_memory": True,
        "permanent_death": True,
        "basic_attack": {"school": "physical", "stat": "atk", "scaling": 1.0, "dice": "d6", "action_text": "melees the target"},
        "specials": {
            "blocking_defence": {
                "action_text": "braces to intercept attacks",
                "timing": "pre_action",
                "effect_id": "blocking_defence",
                "effect_overrides": {"duration": 1, "redirect_to_pet_id": "self.id"},
            }
        },
        "special_id": "blocking_defence",
        "special_chance": 0.30,
        "display": {
            "war_council": True,
            "label": "Barrens Boar",
            "color": "#AAD372",
            "priority": 25,
        },
    },
    "mana_tide_totem": {
        "id": "mana_tide_totem",
        "template_id": "mana_tide_totem",
        "name": "Mana Tide Totem",
        "entity_type": "totem",
        "hp": 15,
        "duration": 4,
        "max_count": 1,
        "behavior_id": "mana_tide_totem_regen",
        "display": {
            "war_council": True,
            "label": "Mana Tide Totem",
            "color": "#0070DD",
            "priority": 25,
        },
    },
    "capacitor_totem": {
        "id": "capacitor_totem",
        "template_id": "capacitor_totem",
        "name": "Capacitor Totem",
        "entity_type": "totem",
        "hp": 5,
        "max_count": 1,
        "behavior_id": "capacitor_totem_discharge",
        "display": {
            "war_council": True,
            "label": "Capacitor Totem",
            "color": "#0070DD",
            "priority": 25,
        },
    },
}
