PETS = {
    "imp": {
        "id": "imp",
        "name": "Imp",
        "hp": 45,
        "school": "magical",
        "max_count": 3,
        "behavior_id": "imp_firebolt",
        "behavior": "imp_firebolt",
        "display": {
            "war_council": True,
            "label": "Imp",
            "color": "#FF7A59",
            "priority": 20,
        },
    },
    "shadowfiend": {
        "id": "shadowfiend",
        "name": "Shadowfiend",
        "hp": 75,
        "school": "physical",
        "duration": 5,
        "max_count": 1,
        "behavior_id": "shadowfiend_melee_mana",
        "behavior": "shadowfiend_melee_mana",
        "display": {
            "war_council": True,
            "label": "Shadowfiend",
            "color": "#8C7AE6",
            "priority": 30,
        },
    },
    "frostsaber": {
        "id": "frostsaber",
        "template_id": "frostsaber",
        "name": "Frostsaber",
        "hp": 20,
        "atk": 6,
        "int": 2,
        "school": "physical",
        "max_count": 1,
        "behavior_id": "hunter_basic_plus_special",
        "summon_group": "hunter_companion",
        "persistent_owner_memory": True,
        "permanent_death": True,
        "basic_attack": {"school": "physical", "stat": "atk", "scaling": 1.0, "dice": "d4"},
        "special_id": "bite",
        "special_chance": 0.30,
        "display": {
            "war_council": True,
            "label": "Frostsaber",
            "color": "#AAD372",
            "priority": 25,
        },
    },
    "emerald_serpent": {
        "id": "emerald_serpent",
        "template_id": "emerald_serpent",
        "name": "Emerald Serpent",
        "hp": 15,
        "atk": 4,
        "int": 10,
        "school": "magical",
        "max_count": 1,
        "behavior_id": "hunter_basic_plus_special",
        "summon_group": "hunter_companion",
        "persistent_owner_memory": True,
        "permanent_death": True,
        "basic_attack": {"school": "physical", "stat": "atk", "scaling": 1.0, "dice": "d4"},
        "special_id": "lightning_breath",
        "special_chance": 0.30,
        "display": {
            "war_council": True,
            "label": "Emerald Serpent",
            "color": "#AAD372",
            "priority": 25,
        },
    },
    "barrens_boar": {
        "id": "barrens_boar",
        "template_id": "barrens_boar",
        "name": "Barrens Boar",
        "hp": 30,
        "atk": 4,
        "int": 0,
        "school": "physical",
        "max_count": 1,
        "behavior_id": "hunter_basic_plus_special",
        "summon_group": "hunter_companion",
        "persistent_owner_memory": True,
        "permanent_death": True,
        "basic_attack": {"school": "physical", "stat": "atk", "scaling": 1.0, "dice": "d6"},
        "special_id": "blocking_defence",
        "special_chance": 0.30,
        "display": {
            "war_council": True,
            "label": "Barrens Boar",
            "color": "#AAD372",
            "priority": 25,
        },
    }
}
